apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: myproject
  labels:
    app: "airflow"
    tier: "frontend"
spec:
  type: NodePort # Можно ClusterIP, если доступ извне не нужен
  selector:
    app: "airflow"
    tier: "frontend"
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # порт на ноде, через который можно будет обратиться (при желании)
