apiVersion: v1
kind: ConfigMap
metadata:
  name: myproject-config
  namespace: myproject
  labels:
    app: "myproject"
    component: "config"
data:
  POSTGRES_USER: "postgres_user"
  POSTGRES_DB: "postgres_db"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres_user:postgres_password@postgres:5432/postgres_db"
