version: '3'

networks:
  general_network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - general_network
    ports:
      - "5432:5432"

  data-service:
    build:
      context: ./data_service
    container_name: data-service
    networks:
      - general_network
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  airflow:
    build:
      context: ./airflow
      dockerfile: good.Dockerfile
    container_name: airflow
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/temperatures:/opt/airflow/temperatures
    networks:
      - general_network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - data-service

volumes:
  postgres_data:
    name: postgres_data
