apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: myproject
  labels:
    app: "postgres"
    component: "storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
